language: python
python:
  - 3.6
  
os: linux
addons:
  apt:
    packages:
      - g++-5
      - gfortran-5
      - gcc

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest numba cython
  - source activate test-environment
  - pip install python-coveralls pytest-cov
  - python compile_all.py
  
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then py.test -vv data/tests.py --cov .;
    else py.test -vv data/tests.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then coveralls;
    fi

notifications:
  email: false
